### ISSUE TITLE
Duplicate entry in search

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Ore#768] opened 2019-03-05 18:21 UTC
**Describe the bug**
A duplicate entry is shown in the search menu.

**To Reproduce**
1. Go to ore.spongepowered.org
2. Search for 'trade'
3. Observe that CJcool06's SafeTrade appears twice

**Expected behavior**
No duplicates.

**Screenshots**
https://i.imgur.com/zJNav6u.png

**Environment:**
 - Desktop
 - Chrome
 -  72.0.3626.121

**Comment by Katrix** [comment] 2019-03-18 11:58
Duplicate of #764

**Closed as completed by Katrix** 2019-03-18 11:58 UTC
Labels: status: accepted, type: bug report
