### ISSUE TITLE
Give a warning if clicking on external link

### ISSUE THREAD

**Issue by Ewoutvans** [SpongePowered/Ore#342] opened 2018-01-06 16:27 UTC
The links for issues, source, license are configurable by the user and could be set to malicieus website. We should add a modal with the full url in display and a disclaimer to inform the user that they are leaving the site and to what site they are going.

**Comment by phase** [comment] 2018-01-06 16:35
Duplicate of #218

**Closed as completed** 2018-01-06 16:59 UTC
Labels: resolution: duplicate

**Comment by mbax** [comment] 2018-01-06 18:11
Thanks for the issue, @Ewoutvans !

Clicking through the above issue will eventually end you at the spot where we merged in code to make this happen. It'll go live soon :)
