### ISSUE TITLE
Ore forum post does not update

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Ore#211] opened 2017-01-26 16:38 UTC
I've observed this for quite a while. When you update a project page, it does not update the forum post to the current state of the page. Rather, it updates it to the previous state. So if I edited a page to say A, then edited it to say B, then edited it to say C, the thread would say Welcome to your new project! followed by A followed by B. To apply current changes, I have to click Edit and click Save again.

**Comment by windy1** [comment] 2017-02-13 17:45
Duplicate of #181

**Closed as completed by windy1** 2017-02-13 17:45 UTC
Labels: type: bug, resolution: duplicate
