### ISSUE TITLE
Be more lenient with session timeouts?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#298] opened 2017-12-18 02:18 UTC
```
22:41 | <⇅N​e​u​m​i​m​T​o​> | >you are preparing a next plugin version release >it takes few minutes to describe changes in the text area field >finally you click publish >409, your session expires >everything lost
-- | -- | --
22:41 | <⇅N​e​u​m​i​m​T​o​> | why
```

Current Master: https://github.com/SpongePowered/Ore/commit/09ff55b85bf11270cc6e487707a3203f019645aa

Deployed build: unknown

**Comment by simon816** [comment] 2018-01-15 22:28
Not sure if anyone else has successfully reproduced this, but from my testing there doesn't seem to be a short expiry. I started creating a project, left the application running for several hours then came back and was successfully able to publish it. (Though, I did get an authentication error, but refreshing seemed to work, could be related).

By the looks of things, a `PendingProject` is cached in the in-memory caching service with no expiry, and the authenticated session cookie lasts for 4 weeks.
Since the cache is in memory it could have purged if the server died/restarted, unlikely though.

**Comment by ryantheleach** [comment] 2018-01-16 00:21
@simon816 did you also test on the new version page?

**Comment by ryantheleach** [comment] 2018-01-16 00:26
@simon816 did you also test on the new version page?
Given simon's feedback, if this exists I don't think it's preventing launch (if it ever was)

**Comment by Katrix** [comment] 2019-01-11 23:51
As said before, pending projects have no timeouts. This was another bug which should be fixed

**Closed as completed by Katrix** 2019-01-11 23:51 UTC
Labels: type: bug, status: input wanted, component: backend
