### ISSUE TITLE
Item duplicates

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Ore#771] opened 2019-03-12 00:31 UTC
Browser: Firefox 66.0b13
Just got 2 duplicates of items in list of plugins.
https://puu.sh/CYD23/72437aa23a.png
https://ore.spongepowered.org/?page=6

They both have same hyperlinks.

**Comment by Katrix** [comment] 2019-03-12 00:32
Duplicate of #768

**Closed as completed by Katrix** 2019-03-12 00:32 UTC
Labels: status: needs testing, type: bug report
