### ISSUE TITLE
"confirm email" is pointless

### ISSUE THREAD

**Issue by jomo** [SpongePowered/Ore#26] opened 2015-03-01 20:55 UTC
I'm not sure why so many websites ask their users to confirm their email or password.
The result is, however, an annoyed user who just copy/pastes it into the second field and there are zero benefits.

**Comment by gratimax** [comment] 2015-03-01 22:02
I originally had a 'confirm password' field, but I switched to confirming an email. If one mistypes a password, they will be able to recover it with the email. In addition, multiple messages or notifications can be sent over email, making it important to confirm. Finally, since the email is not hidden, it's easily to visually confirm, making it less of a burden on the user.

**Comment by jomo** [comment] 2015-03-01 22:05
I understand that, but I'm quite sure I can't be the only one who just copy/pastes that field.

**Comment by Kornagan** [comment] 2015-03-01 22:25
Then ensure that one cannot paste into the confirm field.

**Comment by jomo** [comment] 2015-03-01 22:27
no, that's just horrible. How about just type your email right (or let your browser handle it for you)?
Otherwise you should confirm the username and everything else as well.

**Comment by Kornagan** [comment] 2015-03-01 22:38
no the point of having to confirm your email is that if you mistype your password you can be sure to recover your account.

**Comment by jomo** [comment] 2015-03-01 22:42
I know what the idea is, it's just bad UX. Disabling copy/paste doesn't make this any better.

To solve the problem of recovering, we could send an activation link via email that has to be clicked before the account can be used.

relevant: [how to annoy 99.9% of users in an effort to help the 0.1% who enter their email addresses incorrectly](http://www.90percentofeverything.com/2010/02/25/the-email-confirmation-paste-disabling-antipattern/)

**Comment by gratimax** [comment] 2015-03-01 22:51
I like the "display email right before form submit" idea, I will try to implement that.

**Comment by gratimax** [comment] 2015-03-01 23:08
Actually, here's another idea: Display a checkbox in the form like so:

- [ ] I have confirmed that my email is correct, stop worrying about it!

And the checkbox must be checked in order to submit the form. If it is not checked, then form validation fails. While still annoying, it makes the user possibly chuckle a little and check their email anyway, and has a lower mental bandwidth than requiring submission of the form.

**Comment by jomo** [comment] 2015-03-01 23:11
:+1:
```HTML
<input type="checkbox" required="">
```

**Comment by ryantheleach** [comment] 2015-03-02 01:11
I actually like having to confirm either my email or my password. That said, I do copy and paste the email address occasionally, but only after ensuring that the email address is correct.

Getting it wrong normally means that your username is now irrevocably reserved, and now impossible to recover.

**Comment by GenPage** [comment] 2015-03-24 20:35
I agree with @ryantheleach 

You'd be really surprised how many people incorrectly type in their emails (and its not 0.1%). It doesnt matter about personal preference or how annoying something is. Its performing a function to check about Layer 8 issues. 

:+1: for checkbox "I have confirmed that my email (<email>) is correct, stop worrying about it!"

**Comment by jomo** [comment] 2015-03-24 20:53
> and its not 0.1%

About `0.03%` failed to be delivered on [a site](http://redstoner.com/users) with ~800 users. If that number is just a third of the misspelled emails, it's still below 0.1%.

Anyway, you might also want to take a look at https://github.com/mailcheck/mailcheck

**Comment by gratimax** [comment] 2015-04-16 16:09
Fixed in d0dd3648df4d81

![invalid form](http://puu.sh/hg4eY/cf6427ce18.png).

**Closed by gratimax** 2015-04-16 16:09 UTC
