### ISSUE TITLE
Unexpected exception[ParserRuntimeException: Error while parsing action '

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#109] opened 2016-05-12 14:11 UTC
Browser & Version: `Google Chrome   51.0.2704.7 (Official Build) dev-m (64-bit)
Revision    a8bebc2b0cd3e3018b7c9f6ac698f04dd226abba-refs/branch-heads/2704@{#48}`

Operating System: `Windows 10`

Error message (if applicable): `Unexpected exception[ParserRuntimeException: Error while parsing action 'Root/Sequence/ZeroOrMore/Sequence/Block/FirstOf/Table/Sequence/Optional/Sequence/NodeSequence/Sequence/TableRow/Sequence/OneOrMore/Sequence/TableCell/NodeSequence/Sequence/OneOrMore/Sequence/Inline/Inline_Action1' at input position (line 4, pos 1): <img src="/uploads/default/original/2X/7/7be312ddb41c8699b6b2aa6a940fb369a1c48696.png" width="30" height="30"> **Website** ^ org.pegdown.ParsingTimeoutException]
If you suspect this is a bug, please take a minute to report it to the issue tracker.`

Steps to reproduce:
- Visit https://ore-staging.spongepowered.org/HassanS6000/EssentialCmds

**Comment by simon816** [comment] 2016-05-12 15:33
This seems to be caused by `PegDownProcessor` exceeding the time limit ([Default 2 seconds](https://github.com/sirthias/pegdown/blob/0b9b69f1acfc4489883066f89ff0dca3a0b9febe/src/main/java/org/pegdown/PegDownProcessor.java#L39)).
The timeout can be increased [in the constructor](https://github.com/SpongePowered/Ore/blob/master/app/models/project/Page.scala#L103)

**Comment by windy1** [comment] 2016-05-12 16:54
I feel like there's something else going on here. No page should be taking that long to process.

**Comment by windy1** [comment] 2016-08-19 23:29
According to the issue tracker, this has not occurred in quite a while. Closing for now.

**Closed as completed by windy1** 2016-08-19 23:29 UTC
Labels: type: bug
