### ISSUE TITLE
Can't edit organisation avatar

### ISSUE THREAD

**Issue by Hbeau** [SpongePowered/Ore#685] opened 2018-10-09 19:58 UTC
* Browser: `Firefox`,`Google Chrome`

* Operating System: `Windows 10`

* Error message (if applicable): ``

* Page link: `https://ore.spongepowered.org/<organisationName>`

* Steps to reproduce:

    * Log in your account
    * Create an organisation
    * Click on avatar or "Edit avatar"

When you click on edit avatar for your organisation, nothing happened.

**Comment by felixoi** [comment] 2018-10-09 20:00
Duplicate of https://github.com/SpongePowered/Ore/issues/344

**Closed as completed by felixoi** 2018-10-09 20:00 UTC
Labels: resolution: duplicate
