### ISSUE TITLE
New project isn't shown

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Ore#719] opened 2018-12-11 11:57 UTC
* Browser: `Firefox 63.0.3`

* Operating System: `Arch Linux`

* Page link: `https://puu.sh/CfUK9/0a3a04d0e4.png`

* Steps to reproduce:

    I just published new project, it isn't shown on main page, can't be found using search, it isn't shown in my profile page. You can open it using direct link.

Main page: https://puu.sh/CfUK2/e596551b46.png
Search: https://puu.sh/CfUK9/0a3a04d0e4.png
Profile page: https://puu.sh/CfUJn/7866b96198.png

**Comment by felixoi** [comment] 2018-12-12 10:48
The only version of your plugin is not marked as recommended. To save us from Ore going down we implemented something that just hides the plugin then. This safety mechanism is the cause of your issue. Can you tell me if you did something to not mark it as recommended? Normally it should be recommended automatically and I couldn't reproduce this issue locally.

**Comment by XakepSDK** [comment] 2018-12-12 10:56
I did not changed anything in submit form.

I just added new version and it seems, that it shows now.

**Comment by felixoi** [comment] 2018-12-12 10:59
Yeah we set your version manually to recommended. I'll close this for now since I cannot reproduce it.

**Closed as completed by felixoi** 2018-12-12 10:59 UTC
Labels: type: bug
