### ISSUE TITLE
Unexpected exception[NoSuchFileException: /home/ore/files/plugins/Revilo/MultiChat/multichat-1.5.jar]

### ISSUE THREAD

**Issue by Tenelia** [SpongePowered/Ore#266] opened 2017-06-04 04:43 UTC
Indeed it is as the title says: Unexpected exception[NoSuchFileException: /home/ore/files/plugins/Revilo/MultiChat/multichat-1.5.jar]

Taken from https://ore.spongepowered.org/Revilo/MultiChat/versions

**Comment by windy1** [comment] 2017-06-07 17:15
Duplicate of #258

**Closed as completed by windy1** 2017-06-07 17:15 UTC
Labels: resolution: duplicate
