### ISSUE TITLE
Project creation timed out when owner set as Org

### ISSUE THREAD

**Issue by ItsDoot** [SpongePowered/Ore#626] opened 2018-08-13 03:15 UTC
* Browser: `Google Chrome`

* Operating System: `Windows 10`

* Error message (if applicable): `N/A`

* Page link: `https://ore.spongepowered.org/new`

* Steps to reproduce:

    * Step 1: Upload and sign a plugin.
    * Step 2: On the next page, set an organization as the owner.
    * Step 3: Continue through the pages until pressing next on the `Invite Members` page. Upon presisng this button, an error is received: `Project creation timed out, or you have not uploaded a plugin file. `

**Comment by felixoi** [comment] 2018-08-13 05:05
Yeah it's a known issue. The problem is deeper than just a quick fix that's why it's still not fixed.

**Comment by Ewoutvans** [comment] 2018-08-13 07:03
Duplicate of #558

**Closed as completed by Ewoutvans** 2018-08-13 07:03 UTC
Labels: priority: high, component: backend
