### ISSUE TITLE
Organization Management

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Ore#619] opened 2018-08-10 17:01 UTC
AlmuraDev is an organization I setup on Ore.  I can't seem to figure out how to do the following: 
- Add our Avatar icon
- Add notes about our organization

Another issue I've seen, when I added "AlmuraDev" to a project, it says "(Invited as Developer)" next to the AlmuraDev name.  How can I make this go away?

![image](https://user-images.githubusercontent.com/1034770/43971040-3da4c366-9c95-11e8-9975-21121e1b3948.png)

**Comment by Ewoutvans** [comment] 2018-08-13 14:58
PR #632 fixes 
- the 'notes' (tagline) for the organization
- ability to join/leave a project that will remove the Invited

The "Add our Avatar" is duplicate of #344

**Closed as completed** 2018-08-21 20:58 UTC
Labels: component: frontend
