### ISSUE TITLE
Cannot add myself as a developer to a project my organization owns

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#256] opened 2017-04-28 02:05 UTC
![image](https://cloud.githubusercontent.com/assets/18372958/25511445/89cb90a6-2b8c-11e7-87c4-a23ca389aa70.png)

I am able to add other developers which are in the organization just fine though. This occurred with my project [Latch](https://ore.spongepowered.org/IchorPowered/Latch).

I feel representing all developers who are working on the project as important, as it allows users to know who they should talk to and who to relate to the project. I do not necessarily think all organization members should show up though as not all are necessarily working on that project. 

This is the result without me in the project:

![image](https://cloud.githubusercontent.com/assets/18372958/25511612/65145d8c-2b8d-11e7-8775-9025c923600e.png)

**Comment by simon816** [comment] 2017-07-14 21:32
According to the API, you're already marked as an owner/developer (https://ore.spongepowered.org/api/v1/projects/latch)
I think it might be a display issue @windy1

**Comment by phase** [comment] 2018-01-02 08:40
Your role in the project is hidden for some reason. I'm not sure what could have caused it.

**Comment by phase** [comment] 2018-01-02 15:37
I was only able to reproduce this if I hadn't accepted the role. If you invite someone to a role on a _repository_, it will not show they have been invited when you go to edit it. However, that is a different but than the bug you're experiencing, because `is_visible` has always been set to true in my testing.

This brings up some questions: _What are the use cases for `is_visible`? Why have an ability to hide yourself on a project?_ If you're in an organization, you can easily be removed from the project by an admin in the org (or maybe you can do it yourself). I don't see any reason to allow people to hide themselves.

I'm fine with removing `is_visible` from the table and making every role visible.

**Comment by phase** [comment] 2018-01-02 16:09
The first image you posted has been addressed by #312 (and fixed in #313), but the second image has to do with my comment above.

**Closed as completed** 2018-01-03 04:47 UTC
Labels: type: bug, priority: showstopper
